services:
  - type: web
    name: project-repository-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: DATABASE_URL
        fromDatabase:
          name: project-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: project-db
    plan: free
